delete from PRODLIB_PROMOTION where PROMOTION_ID = '46';
delete from PRODLIB_PROMOTION where PROMOTION_ID = '52';
insert into PRODLIB_PROMOTION (PROMOTION_ID,PROMOTION_CODE_ID,PRODUCT_ID,MAP_KEY,DIST_ID,PROMO_START_TIME,PROMO_END_TIME,STATUS,ISDELETED,CREATED_BY,CREATED_TIME,LAST_UPDATED_BY,LAST_UPDATED_TIME ) values ('46','4','PROD_ILP_IB6','ALL',' ',to_date('2016-03-30 00:00:00','yyyy-MM-dd HH24:MI:ss'),to_date('','yyyy-MM-dd HH24:MI:ss'),'A','N','SYSTEM', current_timestamp ,'system', current_timestamp);

delete from PRODLIB_PROMOTION_CODE where PROMOTION_CODE_ID = '11';

DELETE FROM FORM_FRAGMENTS WHERE FORM_FRAG_ID = 'FORM_FRAG_UUID_602';
Insert Into FORM_FRAGMENTS(FORM_FRAG_ID,FRAGMENT_KEY,FRAGMENT_DESC,TEMPLATE,FRAGMENT_TYPE,FRAGMENT_PATH,ISDELETED,CREATED_BY,CREATED_TIME,LAST_UPDATED_BY,LAST_UPDATED_TIME,VERSION_NO,EFF_START_DATE,EFF_END_DATE) values ( 'FORM_FRAG_UUID_602','IB6ProductSummary','Product Summary PDF','','pdf','[DSF] FlexiLink (IB6) V4.2 2018 04 13.pdf', 'N', 'SYSTEM', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP,'1',to_date('01-APR-18','DD-MON-RR'),'');


